repos:

  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0



    hooks:
      - id: terraform-fmt
      - id: shellcheck
      - id: tflint


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-yaml
      - id: check-added-large-files
