---
name: Auto merge
on:
  pull_request:
jobs:
  auto-merge:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_merge.yml@master
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
    with:
      tfcheck: 'ec2-network-mode-awsvpc / Check code format'
...
