name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  ec2-network-mode-awsvpc:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './_example/ec2-network-mode-awsvpc/'
      terraform_version: 1.5.7
  ec2-network-mode-bridge:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './_example/ec2-network-mode-bridge/'
      terraform_version: 1.5.7
  fargate:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './_example/fargate/'
      terraform_version: 1.5.7

