name: tf-checks 
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  ec2-network-mode-awsvpc:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './_example/ec2-network-mode-awsvpc/'
  ec2-network-mode-bridge:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './_example/ec2-network-mode-bridge/'
  fargate:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './_example/fargate/'

